set_property SRC_FILE_INFO {cfile:/home/vladimir/Downloads/FACTOR-I_17.04.2020_bins/project_led.srcs/sources_1/ip/pll/pll.xdc rfile:../../../project_led.srcs/sources_1/ip/pll/pll.xdc id:1 order:EARLY scoped_inst:pll_inst/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/vladimir/Downloads/FACTOR-I_17.04.2020_bins/project_led.srcs/constrs_1/new/LED.xdc rfile:../../../project_led.srcs/constrs_1/new/LED.xdc id:2} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.2
set_property src_info {type:XDC file:2 line:226 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    J19         [get_ports led_1]
set_property src_info {type:XDC file:2 line:229 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    U22         [get_ports sys_clk]
set_property src_info {type:XDC file:2 line:232 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    H19         [get_ports sys_rst_n]
set_property src_info {type:XDC file:2 line:305 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    D1          [get_ports PHY_RESET_N]
set_property src_info {type:XDC file:2 line:309 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    H1          [get_ports PHY_MDC]
set_property src_info {type:XDC file:2 line:313 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    H2          [get_ports PHY_MDIO]
set_property src_info {type:XDC file:2 line:317 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    E5          [get_ports PHY_GTXC]
set_property src_info {type:XDC file:2 line:322 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    A5          [get_ports PHY_RXDV]
set_property src_info {type:XDC file:2 line:326 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    D4          [get_ports PHY_RXC]
set_property src_info {type:XDC file:2 line:330 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    D5          [get_ports PHY_RXER]
set_property src_info {type:XDC file:2 line:334 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    B1          [get_ports PHY_TXEN]
set_property src_info {type:XDC file:2 line:339 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    F4          [get_ports PHY_TXC]
set_property src_info {type:XDC file:2 line:343 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    J4          [get_ports PHY_TXER]
set_property src_info {type:XDC file:2 line:347 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    B5          [get_ports {PHY_RXD[0]}]
set_property src_info {type:XDC file:2 line:348 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    A4          [get_ports {PHY_RXD[1]}]
set_property src_info {type:XDC file:2 line:349 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    B4          [get_ports {PHY_RXD[2]}]
set_property src_info {type:XDC file:2 line:350 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    A2          [get_ports {PHY_RXD[3]}]
set_property src_info {type:XDC file:2 line:351 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    A3          [get_ports {PHY_RXD[4]}]
set_property src_info {type:XDC file:2 line:352 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    C2          [get_ports {PHY_RXD[5]}]
set_property src_info {type:XDC file:2 line:353 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    B2          [get_ports {PHY_RXD[6]}]
set_property src_info {type:XDC file:2 line:354 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    C4          [get_ports {PHY_RXD[7]}]
set_property src_info {type:XDC file:2 line:357 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    C1          [get_ports {PHY_TXD[0]}]
set_property src_info {type:XDC file:2 line:358 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    E1          [get_ports {PHY_TXD[1]}]
set_property src_info {type:XDC file:2 line:359 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    E2          [get_ports {PHY_TXD[2]}]
set_property src_info {type:XDC file:2 line:360 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    F2          [get_ports {PHY_TXD[3]}]
set_property src_info {type:XDC file:2 line:361 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    G4          [get_ports {PHY_TXD[4]}]
set_property src_info {type:XDC file:2 line:362 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    G1          [get_ports {PHY_TXD[5]}]
set_property src_info {type:XDC file:2 line:363 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    G2          [get_ports {PHY_TXD[6]}]
set_property src_info {type:XDC file:2 line:364 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    H4          [get_ports {PHY_TXD[7]}]
set_property src_info {type:XDC file:2 line:378 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    P1          [get_ports bclk]
set_property src_info {type:XDC file:2 line:381 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    P6          [get_ports ddata]
set_property src_info {type:XDC file:2 line:384 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    M1          [get_ports lrck]
set_property src_info {type:XDC file:2 line:391 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    M5          [get_ports envelope]
set_property src_info {type:XDC file:2 line:403 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    M4          [get_ports ser1_rx]
set_property src_info {type:XDC file:2 line:406 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    R3          [get_ports ser1_tx]
set_property src_info {type:XDC file:2 line:409 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    K1          [get_ports ser1_rse]
set_property src_info {type:XDC file:2 line:416 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    L4          [get_ports ser2_rx]
set_property src_info {type:XDC file:2 line:419 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    P3          [get_ports ser2_tx]
set_property src_info {type:XDC file:2 line:422 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    J1          [get_ports ser2_rse]
set_property src_info {type:XDC file:2 line:429 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    N2          [get_ports dds_rst]
set_property src_info {type:XDC file:2 line:432 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    K5          [get_ports dds_sclk]
set_property src_info {type:XDC file:2 line:435 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    L5          [get_ports dds_upd]
set_property src_info {type:XDC file:2 line:438 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    N3          [get_ports dds_data]
set_property src_info {type:XDC file:2 line:445 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    AC26        [get_ports rk_o]
set_property src_info {type:XDC file:2 line:448 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    AB26        [get_ports ru_o]
set_property src_info {type:XDC file:2 line:451 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    Y22         [get_ports rst_adc_o]
set_property src_info {type:XDC file:2 line:454 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    W23         [get_ports conv_o]
set_property src_info {type:XDC file:2 line:458 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    V23         [get_ports clk_adc_o]
set_property src_info {type:XDC file:2 line:462 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    P23         [get_ports {cs_o[0]}]
set_property src_info {type:XDC file:2 line:463 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    P24         [get_ports {cs_o[1]}]
set_property src_info {type:XDC file:2 line:464 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    R25         [get_ports {cs_o[2]}]
set_property src_info {type:XDC file:2 line:465 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    P25         [get_ports {cs_o[3]}]
set_property src_info {type:XDC file:2 line:466 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    T24         [get_ports {cs_o[4]}]
set_property src_info {type:XDC file:2 line:467 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    T25         [get_ports {cs_o[5]}]
set_property src_info {type:XDC file:2 line:468 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    U21         [get_ports {cs_o[6]}]
set_property src_info {type:XDC file:2 line:469 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    V21         [get_ports {cs_o[7]}]
set_property src_info {type:XDC file:2 line:473 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    N21         [get_ports {adc_data_1_i[0]}]
set_property src_info {type:XDC file:2 line:474 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    M24         [get_ports {adc_data_1_i[1]}]
set_property src_info {type:XDC file:2 line:475 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    R26         [get_ports {adc_data_1_i[2]}]
set_property src_info {type:XDC file:2 line:476 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    L22         [get_ports {adc_data_1_i[3]}]
set_property src_info {type:XDC file:2 line:477 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    N26         [get_ports {adc_data_1_i[4]}]
set_property src_info {type:XDC file:2 line:478 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    K22         [get_ports {adc_data_1_i[5]}]
set_property src_info {type:XDC file:2 line:479 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    K25         [get_ports {adc_data_1_i[6]}]
set_property src_info {type:XDC file:2 line:480 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    K21         [get_ports {adc_data_1_i[7]}]
set_property src_info {type:XDC file:2 line:481 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    H21         [get_ports {adc_data_1_i[8]}]
set_property src_info {type:XDC file:2 line:482 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    G20         [get_ports {adc_data_1_i[9]}]
set_property src_info {type:XDC file:2 line:483 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    J25         [get_ports {adc_data_1_i[10]}]
set_property src_info {type:XDC file:2 line:484 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    G22         [get_ports {adc_data_1_i[11]}]
set_property src_info {type:XDC file:2 line:485 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    F23         [get_ports {adc_data_1_i[12]}]
set_property src_info {type:XDC file:2 line:486 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    H26         [get_ports {adc_data_1_i[13]}]
set_property src_info {type:XDC file:2 line:487 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    E25         [get_ports {adc_data_1_i[14]}]
set_property src_info {type:XDC file:2 line:488 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    E26         [get_ports {adc_data_1_i[15]}]
set_property src_info {type:XDC file:2 line:491 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    D26         [get_ports {adc_data_2_i[0]}]
set_property src_info {type:XDC file:2 line:492 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    D25         [get_ports {adc_data_2_i[1]}]
set_property src_info {type:XDC file:2 line:493 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    G26         [get_ports {adc_data_2_i[2]}]
set_property src_info {type:XDC file:2 line:494 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    E23         [get_ports {adc_data_2_i[3]}]
set_property src_info {type:XDC file:2 line:495 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    F22         [get_ports {adc_data_2_i[4]}]
set_property src_info {type:XDC file:2 line:496 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    J26         [get_ports {adc_data_2_i[5]}]
set_property src_info {type:XDC file:2 line:497 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    G21         [get_ports {adc_data_2_i[6]}]
set_property src_info {type:XDC file:2 line:498 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    H22         [get_ports {adc_data_2_i[7]}]
set_property src_info {type:XDC file:2 line:499 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    J21         [get_ports {adc_data_2_i[8]}]
set_property src_info {type:XDC file:2 line:500 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    K26         [get_ports {adc_data_2_i[9]}]
set_property src_info {type:XDC file:2 line:501 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    K23         [get_ports {adc_data_2_i[10]}]
set_property src_info {type:XDC file:2 line:502 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    M26         [get_ports {adc_data_2_i[11]}]
set_property src_info {type:XDC file:2 line:503 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    L23         [get_ports {adc_data_2_i[12]}]
set_property src_info {type:XDC file:2 line:504 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    P26         [get_ports {adc_data_2_i[13]}]
set_property src_info {type:XDC file:2 line:505 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    M25         [get_ports {adc_data_2_i[14]}]
set_property src_info {type:XDC file:2 line:506 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    N22         [get_ports {adc_data_2_i[15]}]
