# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/vladimir/FACTOR2_bins/project_led.srcs/sources_1/ip/ila_eth_tx/ila_eth_tx.xci
# IP: The module: 'ila_eth_tx' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/vladimir/FACTOR2_bins/project_led.srcs/sources_1/ip/ila_eth_tx/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_eth_tx'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/vladimir/FACTOR2_bins/project_led.srcs/sources_1/ip/ila_eth_tx/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_eth_tx'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/vladimir/FACTOR2_bins/project_led.srcs/sources_1/ip/ila_eth_tx/ila_eth_tx_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_eth_tx'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/vladimir/FACTOR2_bins/project_led.srcs/sources_1/ip/ila_eth_tx/ila_eth_tx.xci
# IP: The module: 'ila_eth_tx' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/vladimir/FACTOR2_bins/project_led.srcs/sources_1/ip/ila_eth_tx/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_eth_tx'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/vladimir/FACTOR2_bins/project_led.srcs/sources_1/ip/ila_eth_tx/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_eth_tx'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/vladimir/FACTOR2_bins/project_led.srcs/sources_1/ip/ila_eth_tx/ila_eth_tx_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_eth_tx'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
