# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/vladimir/FACTOR2_bins/project_led.srcs/sources_1/ip/fifo_arp/fifo_arp.xci
# IP: The module: 'fifo_arp' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/vladimir/FACTOR2_bins/project_led.srcs/sources_1/ip/fifo_arp/fifo_arp.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_arp'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/vladimir/FACTOR2_bins/project_led.srcs/sources_1/ip/fifo_arp/fifo_arp_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_arp'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/vladimir/FACTOR2_bins/project_led.srcs/sources_1/ip/fifo_arp/fifo_arp.xci
# IP: The module: 'fifo_arp' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/vladimir/FACTOR2_bins/project_led.srcs/sources_1/ip/fifo_arp/fifo_arp.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_arp'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/vladimir/FACTOR2_bins/project_led.srcs/sources_1/ip/fifo_arp/fifo_arp_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_arp'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
