# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/LED.xdc

# IP: ip/fifo_ser/fifo_ser.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_ser || ORIG_REF_NAME==fifo_ser} -quiet] -quiet

# IP: ip/pll/pll.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pll || ORIG_REF_NAME==pll} -quiet] -quiet

# XDC: ip/pll/pll_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pll || ORIG_REF_NAME==pll} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/pll/pll.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pll || ORIG_REF_NAME==pll} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/pll/pll_ooc.xdc
