# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/vladimir/FACTOR2_bins/project_led.srcs/sources_1/ip/pll_dac_1/pll_dac.xci
# IP: The module: 'pll_dac' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/vladimir/FACTOR2_bins/project_led.srcs/sources_1/ip/pll_dac_1/pll_dac_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_dac'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/vladimir/FACTOR2_bins/project_led.srcs/sources_1/ip/pll_dac_1/pll_dac.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_dac'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/vladimir/FACTOR2_bins/project_led.srcs/sources_1/ip/pll_dac_1/pll_dac_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_dac'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/vladimir/FACTOR2_bins/project_led.srcs/sources_1/ip/pll_dac_1/pll_dac.xci
# IP: The module: 'pll_dac' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/vladimir/FACTOR2_bins/project_led.srcs/sources_1/ip/pll_dac_1/pll_dac_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_dac'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/vladimir/FACTOR2_bins/project_led.srcs/sources_1/ip/pll_dac_1/pll_dac.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_dac'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/vladimir/FACTOR2_bins/project_led.srcs/sources_1/ip/pll_dac_1/pll_dac_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_dac'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
